#!/usr/bin/env python
"""
Strokes-gained verification gate — the live scorecard path.

Where `audit_sg.py` diagnosed the retired hand-typed tables, this gates the
path the API actually serves: the dispersion-derived surface, the scorecard
conditionals, and the four-category attribution in `scorecard_stats.py`.

    cd backend && uv run python scripts/verify_sg.py

Three gates, all model-independent or self-referential by design:

  1. CONSERVATION — g+p+f+a must equal E_tee − score exactly, per hole, on
     every branch of the reconstruction (GIR/non-GIR, par 3/4/5, penalties,
     hole-outs, missing buckets, interpolated and clamped handicaps). Pure
     arithmetic; tolerance is float noise.

  2. TOTALITY — no scorecard a client can legally send may raise. The
     retired implementation crashed on handicap > 18 with an unrecorded
     first putt on a GIR hole, and the failure silently dropped the whole
     round's stats row.

  3. SELF-PLAY ZERO-MEAN — rounds *generated by the model itself*, scored
     through the reconstruction, must average ~0 in every category. This
     tests attribution alone: whatever the surface thinks of real golfers,
     a player who plays exactly like the model must not be told otherwise.
     Tolerances cover Monte Carlo noise plus bucket quantisation (the
     reconstruction sees first putts as tap_in/short/mid/long, as users
     enter them).

A fourth section REPORTS reality alignment — bracket-average scorecards vs
measured aggregates — without gating. That residual is the solver's putting /
landing-distribution shortfall documented in docs/SG_REBUILD.md, and it gates
nothing until the calibration data exists to close it honestly.

Exits non-zero if any gate fails, so CI can carry it.
"""

from __future__ import annotations

import sys
from dataclasses import dataclass
from typing import List, Optional

sys.path.insert(0, str(__import__("pathlib").Path(__file__).resolve().parent.parent))

import numpy as np

from app.core import published
from app.core.empirical import BRACKETS, REFERENCE_COURSE, aggregates_for
from app.core.expected_strokes import (
    MAX_PUTT_FT,
    SEED,
    simulate_holes,
    simulate_putt_counts,
)
from app.core.scorecard_stats import calculate_hole_sg, calculate_round_stats
from app.core.surface_cache import get_conditionals, get_surface
from app.models.round import HoleResult


@dataclass
class Check:
    name: str
    passed: bool
    detail: str


results: List[Check] = []


def report(name: str, passed: bool, detail: str = "") -> None:
    results.append(Check(name, passed, detail))


def rule(title: str) -> None:
    print(f"\n{'─' * 72}\n{title}\n{'─' * 72}")


def hole(
    n: int, par: int, yd: Optional[int], score: int, putts: int,
    fw: Optional[bool], gir: Optional[bool],
    fp: Optional[str] = None, pen: int = 0,
) -> HoleResult:
    return HoleResult(
        hole_number=n, par=par, yardage=yd, score=score, putts=putts,
        fairway=fw, gir=gir, first_putt=fp, penalty_strokes=pen,
    )


# ──────────────────────────────────────────────────────────────────────────────
# 1. Conservation
# ──────────────────────────────────────────────────────────────────────────────

rule("1. Conservation: g+p+f+a = E_tee − score, exactly, on every branch")

SCENARIOS = [
    ("par4 GIR 2-putt",            hole(1, 4, 400, 4, 2, True, True, "mid")),
    ("par4 GIR 3-putt long",       hole(1, 4, 400, 5, 3, True, True, "long")),
    ("par4 nonGIR chip 2-putt",    hole(1, 4, 400, 5, 2, False, False, "short")),
    ("par4 nonGIR no bucket",      hole(1, 4, 400, 5, 2, False, False, None)),
    ("par4 GIR no bucket",         hole(1, 4, 400, 4, 2, True, True, None)),
    ("par4 fairway unrecorded",    hole(1, 4, 400, 4, 2, None, True, "mid")),
    ("par4 2 penalties",           hole(1, 4, 400, 8, 2, False, False, "short", 2)),
    ("par4 chip-in (0 putts)",     hole(1, 4, 400, 4, 0, True, False, None)),
    ("par4 holed approach",        hole(1, 4, 380, 2, 0, True, True, None)),
    ("par3 GIR 2-putt",            hole(1, 3, 170, 3, 2, None, True, "mid")),
    ("par3 nonGIR",                hole(1, 3, 170, 4, 2, None, False, "short")),
    ("par3 nonGIR no bucket",      hole(1, 3, 170, 4, 2, None, False, None)),
    ("par3 penalty",               hole(1, 3, 170, 5, 2, None, False, "short", 1)),
    ("par5 GIR 2-putt",            hole(1, 5, 520, 5, 2, True, True, "mid")),
    ("par5 nonGIR",                hole(1, 5, 520, 6, 2, False, False, "short")),
    ("par5 blowup 3 pen",          hole(1, 5, 520, 11, 3, False, False, "long", 3)),
    ("par5 no yardage",            hole(1, 5, None, 6, 2, True, False, "mid")),
    ("par4 big number",            hole(1, 4, 460, 10, 4, False, False, "long", 1)),
]

HANDICAPS = [0.0, 4.2, 5.0, 7.3, 10.0, 14.9, 18.0, 19.0, 22.4, 25.0, 30.0, 54.0]

worst = 0.0
count = 0
for hcp in HANDICAPS:
    surface = get_surface(hcp)
    cond = get_conditionals(hcp)
    for name, h in SCENARIOS:
        cat = calculate_hole_sg(h, surface, cond)
        total = sum(cat.values())
        yardage = float(h.yardage or {3: 150, 4: 400, 5: 500}[h.par])
        want = surface.strokes(yardage, "tee") - h.score
        gap = abs(total - want)
        worst = max(worst, gap)
        count += 1

print(f"   {count} scenario × handicap combinations, worst |gap| = {worst:.2e}")
report("conservation", worst < 1e-9, f"worst gap {worst:.2e} over {count} cases")


# ──────────────────────────────────────────────────────────────────────────────
# 2. Totality — nothing a client can legally send may raise
# ──────────────────────────────────────────────────────────────────────────────

rule("2. Totality: no legal scorecard raises (the old path crashed at hcp>18)")

failures = []
for hcp in [0, 17, 18, 18.5, 19, 22, 25, 28, 36, 54]:
    try:
        stats = calculate_round_stats(
            [
                hole(1, 4, 400, 5, 2, True, True, None),      # GIR, no bucket
                hole(2, 3, 160, 3, 1, None, True, None),      # GIR, no bucket
                hole(3, 5, 550, 7, 2, False, False, None),    # miss, no bucket
                hole(4, 4, 310, 3, 0, None, False, None),     # chip-in
                hole(5, 4, 420, 9, 3, False, False, "long", 2),
            ],
            handicap=float(hcp),
        )
        for k in ("sg_putting", "sg_short", "sg_driving", "sg_approach"):
            v = stats[k]
            if v != v or abs(v) > 50:
                failures.append(f"hcp {hcp}: {k}={v}")
    except Exception as e:  # noqa: BLE001 — the point is that nothing raises
        failures.append(f"hcp {hcp}: {type(e).__name__}: {e}")

if failures:
    for f in failures:
        print(f"   FAIL {f}")
else:
    print("   all handicaps 0–54 with unrecorded buckets: no exception, sane values")
report("totality", not failures, f"{len(failures)} failing inputs")


# ──────────────────────────────────────────────────────────────────────────────
# 3. Self-play zero-mean — the attribution test
# ──────────────────────────────────────────────────────────────────────────────

rule("3. Self-play: model-generated rounds must attribute ≈ 0 everywhere")

N_SIM = 1500  # plays of each reference hole, per bracket

def bucket_of(fp_ft: float) -> Optional[str]:
    """Mirror the entry UI bands: <3 / 3-10 / 10-25 / 25+ feet."""
    if fp_ft <= 3.0:
        return "tap_in"
    if fp_ft <= 10.0:
        return "short"
    if fp_ft <= 25.0:
        return "mid"
    return "long"

# Strokes per round. G and F are solved and held strict everywhere; so are
# all categories through 10 handicap. P and A at 15–25 carry a KNOWN-OPEN
# transfer of up to ~±1: the model prices expected greenside disasters
# (failed bunker escapes) into P's baseline while the realized extra strokes
# land in A's count, and the walk-on chip assumption pulls the other way.
# The Phase-3 per-hole sampler in docs/SG_REBUILD.md resolves it; the ceiling
# here only stops it regressing further while that lands.
TOL_CAT = 0.35
TOL_PA_HIGH = 1.25  # regression ceiling for the known-open P/A transfer
TOL_TOTAL = 0.50  # sum of categories vs E_tee − score

self_play_fail = []
print(f"   {'hcp':>4} {'G':>7} {'P':>7} {'F':>7} {'A':>7} {'total':>7}   (per-round means, {N_SIM} rounds)")
for hcp in BRACKETS:
    surface = get_surface(hcp)
    cond = get_conditionals(hcp)
    rng = np.random.default_rng(SEED + 4)

    sums = {"g": np.zeros(N_SIM), "p": np.zeros(N_SIM), "f": np.zeros(N_SIM), "a": np.zeros(N_SIM)}
    identity = np.zeros(N_SIM)  # Σ (E_tee − score); the categories must sum to it

    for i, ref in enumerate(REFERENCE_COURSE):
        sim = simulate_holes(surface, ref.yards, N_SIM, rng)
        putts = simulate_putt_counts(surface, sim.first_putt_ft, rng)
        gir = sim.shots_to_green <= (ref.par - 2)
        # The scorecard's own bound: HoleResult caps score at 15 (a player
        # picks up). Truncation applies to entry and identity alike, so
        # conservation still holds exactly; the mean shifts it causes are
        # well inside the gate tolerances.
        score = np.minimum(sim.shots_to_green + putts, 15)
        putts = np.minimum(putts, score - 1)
        pens = np.minimum(sim.penalties, 9)
        e_tee = surface.strokes(ref.yards, "tee")

        for j in range(N_SIM):
            h = hole(
                n=(i % 18) + 1,
                par=ref.par,
                yd=ref.yards,
                score=int(score[j]),
                putts=int(putts[j]),
                fw=bool(sim.fw_hit[j]) if ref.par > 3 else None,
                gir=bool(gir[j]),
                fp=bucket_of(float(sim.first_putt_ft[j])) if putts[j] > 0 else None,
                pen=int(pens[j]),
            )
            cat = calculate_hole_sg(h, surface, cond)
            for k in sums:
                sums[k][j] += cat[k]
            identity[j] += e_tee - score[j]

    means = {k: float(np.mean(v)) for k, v in sums.items()}
    total_mean = float(np.mean(sums["g"] + sums["p"] + sums["f"] + sums["a"]))
    print(
        f"   {hcp:>4} {means['g']:>+7.2f} {means['p']:>+7.2f} "
        f"{means['f']:>+7.2f} {means['a']:>+7.2f} {total_mean:>+7.2f}"
    )

    for k, m in means.items():
        tol = TOL_PA_HIGH if (k in ("p", "a") and hcp >= 15) else TOL_CAT
        if abs(m) > tol:
            self_play_fail.append(f"hcp {hcp}: category {k.upper()} mean {m:+.2f} (tol ±{tol})")
    if abs(total_mean) > TOL_TOTAL:
        self_play_fail.append(f"hcp {hcp}: total mean {total_mean:+.2f} (tol ±{TOL_TOTAL})")

    # And the identity must hold round-by-round, not just on average.
    ident_gap = float(np.max(np.abs((sums["g"] + sums["p"] + sums["f"] + sums["a"]) - identity)))
    if ident_gap > 1e-6:
        self_play_fail.append(f"hcp {hcp}: per-round conservation gap {ident_gap:.2e}")

for f in self_play_fail:
    print(f"   FAIL {f}")
report("self-play zero-mean", not self_play_fail, f"{len(self_play_fail)} deviations")


# ──────────────────────────────────────────────────────────────────────────────
# 4. Reality alignment — REPORT ONLY
# ──────────────────────────────────────────────────────────────────────────────

rule("4. Reality alignment (report only — see docs/SG_REBUILD.md, not a gate)")

print(
    "   A bracket-average scorecard should read 0.00 everywhere. The residual\n"
    "   below is the surface's remaining calibration gap (putting level and\n"
    "   on-green landing distribution), NOT an attribution artifact:\n"
)
print(f"   {'hcp':>4} {'G':>7} {'P':>7} {'F':>7} {'A':>7} {'total':>7}")
for hcp in BRACKETS:
    agg = aggregates_for(hcp)
    n_gir = round(agg.gir_pct * 18)
    drv = [i for i, rh in enumerate(REFERENCE_COURSE) if rh.par > 3]
    n_fw = round(agg.fairway_pct * len(drv))
    total_putts = round(agg.avg_putts)
    total_score = round(agg.avg_score)
    pens = round(published.interpolate(published.PENALTY_STROKES_PER_ROUND, hcp))

    order = sorted(range(18), key=lambda i: REFERENCE_COURSE[i].yards)
    gir_set = set(order[:n_gir])
    fw_set = set(drv[:n_fw])

    putts = [2] * 18
    d = total_putts - 36
    i = 0
    while d != 0 and i < 18:
        putts[i] += 1 if d > 0 else -1
        d += -1 if d > 0 else 1
        i += 1
    bucket = {0: None, 1: "short", 2: "mid", 3: "long"}

    base = []
    for i, rh in enumerate(REFERENCE_COURSE):
        stg = (rh.par - 2) + (0 if i in gir_set else 1)
        base.append(stg + putts[i])
    extra = total_score - sum(base)
    non_gir = [i for i in range(18) if i not in gir_set] or list(range(18))
    j = 0
    while extra != 0:
        base[non_gir[j % len(non_gir)]] += 1 if extra > 0 else -1
        extra += -1 if extra > 0 else 1
        j += 1
    pen_list = [0] * 18
    for k in range(min(pens, len(non_gir))):
        pen_list[non_gir[k]] = 1

    holes = [
        hole(
            i + 1, rh.par, rh.yards, base[i], putts[i],
            (i in fw_set) if rh.par > 3 else None,
            i in gir_set, bucket[putts[i]], pen_list[i],
        )
        for i, rh in enumerate(REFERENCE_COURSE)
    ]
    stats = calculate_round_stats(holes, float(hcp))
    tot = stats["sg_putting"] + stats["sg_short"] + stats["sg_driving"] + stats["sg_approach"]
    print(
        f"   {hcp:>4} {stats['sg_putting']:>+7.2f} {stats['sg_short']:>+7.2f} "
        f"{stats['sg_driving']:>+7.2f} {stats['sg_approach']:>+7.2f} {tot:>+7.2f}"
    )

print(
    "\n   Closing this residual is calibration work (first-putt distance on\n"
    "   GIR, three-putt rates), tracked in SG_REBUILD.md — no attribution\n"
    "   change can fix it and none should try."
)


# ──────────────────────────────────────────────────────────────────────────────
# Summary
# ──────────────────────────────────────────────────────────────────────────────

rule("Summary")
failed = [c for c in results if not c.passed]
for c in results:
    print(f"   [{'PASS' if c.passed else 'FAIL'}] {c.name:<28} {c.detail}")
print(f"\n   {len(results) - len(failed)} of {len(results)} gates passing.")

sys.exit(1 if failed else 0)
